development:
  host: 101.10.10.5
  port: 389
  attribute: sAMAccountName
  base: dc=contoso,dc=com
  admin_user: "imperator"
  admin_password: Password
  ssl: false
  group_base: ou=workers,dc=contoso,dc=com
  # <<: *AUTHORIZATIONS

test:
  host: localhost
  port: 3389
  attribute: cn
  base: ou=people,dc=test,dc=com
  admin_user: cn=admin,dc=test,dc=com
  admin_password: admin_password
  ssl: simple_tls
  # <<: *AUTHORIZATIONS

production:
  host: localhost
  port: 636
  attribute: cn
  base: ou=people,dc=test,dc=com
  admin_user: cn=admin,dc=test,dc=com
  admin_password: admin_password
  ssl: start_tls
  # <<: *AUTHORIZATIONS
